
stages:
  - build
  - test
  - bench


nightly_benchmarks_binius:
  stage: bench
  tags:
    - binius-nightly-bench  # runs on specific machine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'  # Run on schedule
      when: always
      allow_failure: false
  before_script:
    - source ~/.profile
    - source ~/.bashrc
    - export CARGO_HOME="${HOME}/.cargo"
    - export RUSTUP_HOME="${HOME}/.rustup"
    - env

    - if ! grep -q avx512 /proc/cpuinfo; then echo "Error, AVX-512 instruction is not available" >&2; exit 1; fi

    - lscpu
    - rustc --version
    - rustup update
    - rustup install nightly
    - rustup default nightly
    - rustc --version
    - cargo --version
    - mkdir -p results

  script:
    - echo "Run Nightly Benchmark for Binius"
    - ls -lah
    - git clone --branch anexj/add_examples_for_benchmarking https://gitlab.com/IrreducibleOSS/binius.git
    - cd binius
    - ls -lah
    - git status
    - python3 --version
    # TODO: do we need to update arguments?
    - python3 scripts/nightly_benchmarks.py --export-hashers ../results/index-1.mdx --export-binary-ops ../results/index-2.mdx
    # Go back to root directory
    - cd ..
    - cat results/index-1.mdx
    - cat results/index-2.mdx
    # TODO: copy generated reports to: docs/pages/benchmarks/index.mdx - in the binius.xyz
    - cp results/index-1.mdx docs/pages/benchmarks/index.mdx
    - git status
    # Create branch on binius.xyz with updated benchmark results and create an MR
    - BENCH_TIMESTAMP=$(date '+%Y%m%d-%H%M%S')
    - BENCH_HUMAN_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    - BRANCH_NAME="new-bench-${BENCH_TIMESTAMP}"
    - MR_ASSIGN="AnexJ"
    - git checkout -b "${BRANCH_NAME}"

    # Commit the change
    - git config user.email "infra@irreducible.com"
    - git config user.name "Infra CD"
    - git add docs/pages/benchmarks/index.mdx
    - git status
    - gi diff docs/pages/benchmarks/index.mdx

    # TODO: uncomment rest
    # Note: REPO_ACCESS_TOKEN is already created and set up in ulvetanna/biniux.xyz repo for CI/CD to use
    # - git commit -m "Add new bench results run on ${BENCH_HUMAN_TIMESTAMP}"

    # - git status

    # # Push the new branch with MR creation options
    # - git remote add gitlab_origin https://oauth2:${REPO_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    # # https://docs.gitlab.com/ee/topics/git/commit.html#push-options-for-merge-requests
    # - |
    #   git push gitlab_origin "${BRANCH_NAME}" \
    #     -o merge_request.create \
    #     -o merge_request.title="New bench results (${BENCH_HUMAN_TIMESTAMP})" \
    #     -o merge_request.description="New bench results run on ${BENCH_HUMAN_TIMESTAMP}" \
    #     -o merge_request.assign="${MR_ASSIGN}" \
    #     -o merge_request.draft
