name: Build site

on:
  pull_request:
    # Trigger on pull requests to main, or a stack on main
    branches: ["main", "stack/main/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
